# Feign配置
feign:
  # 支持Sentinel
  sentinel:
    enabled: true

  client:
    config:
      # 设置通用配置
      default:
        # client连接超时为100毫秒
        # 连接时间不宜过长，防止依赖服务负载过高情况下活跃连接都在长时间尝试建立连接，建议设置比较短以便快速失败
        connectTimeout: 100
        # client响应超时为1秒
        # 单个接口响应时间不宜过长，建议为1秒，超过1秒的一般都需要优化接口，如果无法优化建议走独立配置
        readTimeout: 1000

  httpclient:
    # 设置单个HOST最大连接数为50个，可根据高峰期调用频率来调整
    maxConnectionsPerRoute: 50
    # 设置全局最大连接数为300个连接，可根据具体有多少FeignClient来决定，比如一个HOST最多50个连接，一个有8个HOST，每个HOST调用频率有高有低，可折中取值300
    maxConnections: 300
    # 设置连接存活时间为900秒，超过该时间后空闲连接会被回收，注意的是如果你通过Java Config覆盖默认ApacheHttpClient，一定要创建定时器来检测无用连接
    timeToLive: 900

spring:
  cloud:
    sentinel:
      # 服务启动时就直接建立心跳，不需要等到第一次访问接口，才连接sentinel
      eager: true
      # 控制台地址
      transport:
        dashboard: localhost:8081

      # 持久化
      datasource:
        ds1: # 随便起名字
          nacos:
            server-addr: localhost:8848
            namespace: DEV
            dataId: gateway # 微服务名称
            groupId: gateway
            data-type: json
            rule-type: flow # 流控规则